kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lare-hpa-autoscaler-clusterrole
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "statefulsets", "deployments/scale", "statefulsets/scale"]
  verbs: ["get", "list", "watch", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lare-hpa-autoscaler-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: lare-hpa-autoscaler
  namespace: autoscale
roleRef:
  kind: ClusterRole
  name: lare-hpa-autoscaler-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lare-hpa-autoscaler
  namespace: autoscale